version: "3.9"

services:
  api:
    build: .
    command: python manage.py runserver 0.0.0.0:8021
    volumes:
      - .:/app
    #TODO make django work on 8080 but enter through 8021
    ports:
      - "8021:8021"
    env_file:
      - .env

