# Generated by Django 5.2 on 2025-05-06 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Actor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("actor_name", models.CharField(max_length=100)),
                ("actor_age", models.PositiveIntegerField()),
                ("actor_nationality", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="CinemaHall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cinema_hall_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("genre_name", models.CharField(max_length=100)),
                ("genre_is_for_adults", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("movie_title", models.CharField(max_length=100)),
                ("movie_duration", models.PositiveIntegerField()),
                ("movie_actors", models.ManyToManyField(to="core.actor")),
                ("movie_genres", models.ManyToManyField(to="core.genre")),
            ],
        ),
        migrations.CreateModel(
            name="MovieScreening",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("movie_screening_date", models.DateTimeField()),
                (
                    "movie_screening_hall",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.cinemahall",
                    ),
                ),
                (
                    "movie_screening_movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.movie"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Seat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seat_row", models.PositiveIntegerField()),
                ("seat_number", models.PositiveIntegerField()),
                (
                    "seat_hall",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.cinemahall",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticket_price", models.PositiveIntegerField()),
                (
                    "ticket_movie_screening",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.moviescreening",
                    ),
                ),
                (
                    "ticket_seat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.seat"
                    ),
                ),
            ],
        ),
    ]
