# Generated by Django 5.2 on 2025-05-07 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_actor_cinemahall_genre_movie_moviescreening_seat_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="genre",
            old_name="genre_is_for_adults",
            new_name="is_for_adults",
        ),
        migrations.RenameField(
            model_name="moviescreening",
            old_name="movie_screening_date",
            new_name="date",
        ),
        migrations.RemoveField(
            model_name="actor",
            name="actor_age",
        ),
        migrations.RemoveField(
            model_name="actor",
            name="actor_name",
        ),
        migrations.RemoveField(
            model_name="actor",
            name="actor_nationality",
        ),
        migrations.RemoveField(
            model_name="cinemahall",
            name="cinema_hall_name",
        ),
        migrations.RemoveField(
            model_name="genre",
            name="genre_name",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="movie_actors",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="movie_duration",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="movie_genres",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="movie_title",
        ),
        migrations.RemoveField(
            model_name="moviescreening",
            name="movie_screening_hall",
        ),
        migrations.RemoveField(
            model_name="moviescreening",
            name="movie_screening_movie",
        ),
        migrations.RemoveField(
            model_name="seat",
            name="seat_hall",
        ),
        migrations.RemoveField(
            model_name="seat",
            name="seat_number",
        ),
        migrations.RemoveField(
            model_name="seat",
            name="seat_row",
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="ticket_movie_screening",
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="ticket_price",
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="ticket_seat",
        ),
        migrations.AddField(
            model_name="actor",
            name="age",
            field=models.PositiveSmallIntegerField(
                default=0, help_text="Age of the actor in years"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="actor",
            name="name",
            field=models.CharField(default="name", max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="actor",
            name="nationality",
            field=models.CharField(default="poland", max_length=54),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cinemahall",
            name="name",
            field=models.CharField(default="name", max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="genre",
            name="name",
            field=models.CharField(default="name", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="movie",
            name="actors",
            field=models.ManyToManyField(related_name="movies", to="core.actor"),
        ),
        migrations.AddField(
            model_name="movie",
            name="duration",
            field=models.PositiveIntegerField(
                default=0, help_text="Duration of the movie in minutes"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="movie",
            name="genres",
            field=models.ManyToManyField(related_name="movies", to="core.genre"),
        ),
        migrations.AddField(
            model_name="movie",
            name="title",
            field=models.CharField(default="title", max_length=185),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="moviescreening",
            name="hall",
            field=models.ForeignKey(
                default="hall",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="movie_screening",
                to="core.cinemahall",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="moviescreening",
            name="movie",
            field=models.ForeignKey(
                default="movie",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="movie_screening",
                to="core.movie",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="seat",
            name="hall",
            field=models.ForeignKey(
                default="hall",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="seat",
                to="core.cinemahall",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="seat",
            name="number",
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="seat",
            name="row",
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ticket",
            name="movie_screening",
            field=models.ForeignKey(
                default="movie",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ticket",
                to="core.moviescreening",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ticket",
            name="price",
            field=models.PositiveSmallIntegerField(
                default=0, help_text="Price of the ticket in PLN"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ticket",
            name="seat",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ticket",
                to="core.seat",
            ),
        ),
    ]
