name: Lint

on: [push, pull_request]

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install dependencies
        run : |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint black
        run: black --check --diff core
      - name: Lint isort
        run: isort --profile black --check-only core
