name: Tests

on: push

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Run tests
        env:
          DJANGO_SECRET_KEY: 'testing-django-key'
          POSTGRES_PASSWORD: 'test-pass'
          POSTGRES_NAME: 'postgres'
          POSTGRES_USER: 'postgres'
        run: make test